name: Build, Test and Deploy Nuget package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  SOLUTION_FILE: JohnVerbiest.TransformOnBuild.MSBuild.Task.sln

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true

    - name: Install Dotnet Framework
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.6.1'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1

    - name: Restore Packages
      run: nuget restore ${{ env.SOLUTION_FILE }}
        
    - name: Build Project
      run: |
        msbuild.exe ${{ env.SOLUTION_FILE }}

    - name: Test Project
      run: |
        vstest.console.exe **/*.Test.dll

    - name: Nuget Pack
      run: nuget pack -Version ${{ steps.gitversion.outputs.nuGetVersionV2 }} JohnVerbiest.TransformOnBuild.nuspec

    - name: Upload nuget package to artifact folder
      uses: actions/upload-artifact@v2
      with: 
        name: packages
        path: '**/JohnVerbiest.TransformOnBuild*.nupkg'
  
    - name: Publish nuget package
      if: startsWith(github.ref, 'refs/heads/master')
      run: nuget push **/JohnVerbiest.TransformOnBuild*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
