name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SOLUTION_FILE: JohnVerbiest.TransformOnBuild.MSBuild.Task.sln
  TEST_FILE: JohnVerbiest.TransformOnBuild.MSBuild.Task.Test\TextTemplate1.txt

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    
    - name: Restore Packages
      run: nuget restore ${{ env.SOLUTION_FILE }}
    
    - name: Remove test file ${{ env.TEST_FILE }}
      uses: JesseTG/rm@v1.0.2
      with:
        path: ${{ env.TEST_FILE }}
    
    - name: Build Project
      run: |
        msbuild.exe ${{ env.SOLUTION_FILE }}

    - name: Read test file ${{ env.TEST_FILE }}
      uses: juliangruber/read-file-action@v1
      with:
        path: ${{ env.TEST_FILE }}

